version: '3'
services:
  api:
    container_name: api
    build: .
    ports:
      - "5000:5000"
    environment:
      API_PORT: 5000
      DB_URL: mongodb+srv://admin:qwerty123@cluster0.md5gtyj.mongodb.net/?retryWrites=true&w=majority
      TOKEN_SECRET: qwerty123
      ACCESS_TOKEN_EXP: 5m
      REFRESH_TOKEN_EXT: 12h
    networks:
      - default